# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubWindow(object):
    def setupUi(self, SubWindow):
        SubWindow.setObjectName("SubWindow")
        SubWindow.resize(602, 312)
        self.centralwidget = QtWidgets.QWidget(SubWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 240, 381, 31))
        self.progressBar.setStyleSheet("QProgressBar{\n"
                                       "    border-radius:10px;\n"
                                       "    text-align: center;\n"
                                       "    font: 75 13pt \"Berlin Sans FB Demi\";\n"
                                       "    background-color: rgb(200, 200, 200);\n"
                                       "}\n"
                                       "QProgressBar::chunk{\n"
                                       "    border-radius:10px;\n"
                                       "    background-color: rgb(255, 170, 0);\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(40, 100, 101, 101))
        self.gif.setText("")
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \"Tw Cen MT Condensed Extra Bold\";\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -10, 621, 331))
        self.background.setText("")
        self.background.setPixmap(
            QtGui.QPixmap("D:/python/AE/image/train.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.raise_()
        self.progressBar.raise_()
        self.gif.raise_()
        self.label.raise_()
        SubWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SubWindow)
        self.statusbar.setObjectName("statusbar")
        SubWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SubWindow)
        QtCore.QMetaObject.connectSlotsByName(SubWindow)

    def retranslateUi(self, SubWindow):
        _translate = QtCore.QCoreApplication.translate
        SubWindow.setWindowTitle(_translate("SubWindow", "MainWindow"))
        self.label.setText(_translate("SubWindow", "Retraining"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SubWindow = QtWidgets.QMainWindow()
    ui = Ui_SubWindow()
    ui.setupUi(SubWindow)
    SubWindow.show()
    sys.exit(app.exec_())
