# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.datain = QtWidgets.QLabel(self.centralwidget)
        self.datain.setGeometry(QtCore.QRect(380, 30, 51, 61))
        self.datain.setText("")
        # self.datain.setPixmap(QtGui.QPixmap(
        # "D:/python/AE/image/datain.png"))
        self.datain.setScaledContents(True)
        self.datain.setObjectName("datain")
        self.light = QtWidgets.QLabel(self.centralwidget)
        self.light.setGeometry(QtCore.QRect(510, 20, 71, 71))
        self.light.setText("")
        # self.light.setPixmap(QtGui.QPixmap(
        #     "D:/python/AE/image/Light-Bulb-PNG-Pic.png"))
        self.light.setScaledContents(True)
        self.light.setObjectName("light")
        self.buffer = QtWidgets.QLabel(self.centralwidget)
        self.buffer.setGeometry(QtCore.QRect(660, 30, 61, 61))
        self.buffer.setText("")
        # self.buffer.setPixmap(QtGui.QPixmap("D:/python/AE/image/buffer.png"))
        self.buffer.setScaledContents(True)
        self.buffer.setObjectName("buffer")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 100, 751, 381))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.STOP = QtWidgets.QLabel(self.centralwidget)
        self.STOP.setGeometry(QtCore.QRect(160, 30, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.STOP.sizePolicy().hasHeightForWidth())
        self.STOP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(16)
        self.STOP.setFont(font)
        self.STOP.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.STOP.setStyleSheet("color: rgb(255, 255, 255);\n"
                                "background-color: rgb(255, 0, 0);\n"
                                "border-style: outset;\n"
                                "border-width: 2px;\n"
                                "border-radius: 10px;\n"
                                "border-color: rgb(0, 0, 0);")
        self.STOP.setAlignment(QtCore.Qt.AlignCenter)
        self.STOP.setObjectName("STOP")
        self.START = QtWidgets.QLabel(self.centralwidget)
        self.START.setGeometry(QtCore.QRect(160, 30, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.START.sizePolicy().hasHeightForWidth())
        self.START.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(16)
        self.START.setFont(font)
        self.START.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.START.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(0, 255, 0);\n"
                                 "border-style: outset;\n"
                                 "border-width: 2px;\n"
                                 "border-radius: 10px;\n"
                                 "border-color: rgb(0, 0, 0);")
        self.START.setAlignment(QtCore.Qt.AlignCenter)
        self.START.setObjectName("START")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(-10, -10, 831, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.counter = QtWidgets.QLabel(self.centralwidget)
        self.counter.setGeometry(QtCore.QRect(730, 70, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.counter.setFont(font)
        self.counter.setObjectName("counter")
        self.RE = QtWidgets.QLabel(self.centralwidget)
        self.RE.setGeometry(QtCore.QRect(160, 30, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RE.sizePolicy().hasHeightForWidth())
        self.RE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(16)
        self.RE.setFont(font)
        self.RE.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.RE.setStyleSheet("color: rgb(255, 255, 255);\n"
                              "\n"
                              "background-color: rgb(255, 170, 0);\n"
                              "border-style: outset;\n"
                              "border-width: 2px;\n"
                              "border-radius: 10px;\n"
                              "border-color: rgb(0, 0, 0);")
        self.RE.setAlignment(QtCore.Qt.AlignCenter)
        self.RE.setObjectName("RE")
        self.RE.raise_()
        self.graphicsView.raise_()
        self.START.raise_()
        self.STOP.raise_()
        self.tableWidget.raise_()
        self.datain.raise_()
        self.light.raise_()
        self.buffer.raise_()
        self.counter.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "進入時間"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "已知/未知"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "是否威脅"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "種類"))
        self.STOP.setText(_translate("MainWindow", "STOP"))
        self.START.setText(_translate("MainWindow", "START"))
        self.counter.setText(_translate("MainWindow", "0"))
        self.RE.setText(_translate("MainWindow", "RE"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
